### ISSUE TITLE
看了你项目源码，正在学习，请问怎么关闭eslint，总是莫名其妙的报错，都是规范的问题，稍微改了.vue任何文件一个字就报错了

### ISSUE THREAD

**Issue by gesha96** [wellfrog16/template-vue-admin#1]

**Comment by wellfrog16** [comment]
不用关闭，在.eslintignore文件下，增加忽略目录/src/即可忽略eslint校验
另外不建议关闭eslint，它可以培养你良好的书写习惯，并避免一些常见错误，从而减少bug

**Comment by gesha96** [comment]
感谢您，谢谢，懂了！


------------------ 原始邮件 ------------------
发件人: "wellfrog"<notifications@github.com>;
发送时间: 2019年9月17日(星期二) 中午12:04
收件人: "wellfrog16/template-vue-admin"<template-vue-admin@noreply.github.com>;
抄送: "じLisa"<690941858@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wellfrog16/template-vue-admin] 看了你项目源码，正在学习，请问怎么关闭eslint，总是莫名其妙的报错，都是规范的问题，稍微改了.vue任何文件一个字就报错了 (#1)




Closed #1.
